### ISSUE TITLE
PupulateCustomHeaders method spelled incorrectly

### ISSUE THREAD

**Issue by programystic** [cpoDesign/APIFramework#3]
The _PupulateCustomHeaders_ method in the _ApiWrapper_ class has been spelled incorrectly.

It should be _PopulateCustomHeaders_.

**Comment by alireza-delavari** [comment]
may i fix this?

**Comment by cpoDesign** [comment]
@general73 Thank you for help and PR. @programystic Thank you for reporting the issue.
